version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: tienda_online_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: contraseña123
      MYSQL_ROOT_PASSWORD: root_contraseña123
